---
- name: Update root index.html file
  include_tasks: convert_markdown_to_html.yaml
  vars:
    markdown_file: "{{ root_dir }}/README.md"
    html_file: "{{ docs_dir }}/index.html"

- name: Create guides directory within docs directory if it does not exist
  file:
    path: "{{ docs_dir }}/guides"
    state: directory
    mode: '0755'

# - name: Find all files ending with .md within the guides directory
#   find:
#     paths: "{{ guides_dir }}"
#     patterns: '*.md'
#     recurse: true
#   register: matched

# - name: Convert all Markdown files to html
#   include_tasks: convert_markdown_to_html.yaml
#   vars:
#     markdown_file: "{{ item.path }}"
#     html_file: "{{ docs_dir }}/guides/{{ item.path | replace('.md', '.html') }}"
#   with_items: "{{ matched.files }}"

# - name: Extract file names
#   set_fact:
#     file_names: "{{ matched.files | map(attribute='path') | map('regex_replace', '.*/([^/]+)\\.md$', '\\1') | list }}"

# - name: Update guides index file
#   copy:
#     content: "{{ lookup('template', 'guides_index_template.html.j2') }}"
#     dest: "{{ docs_dir }}/guides/index.html"
#   vars:
#     guides: "{{ file_names }}"
  
- name: Update guides index.html file
  include_tasks: convert_markdown_to_html.yaml
  vars:
    markdown_file: "{{ guides_dir }}/coming_soon.md"
    html_file: "{{ docs_dir }}/guides/index.html"