---
- name: Update root index.html file
  include_tasks: convert_markdown_to_html.yaml
  vars:
    markdown_file: "{{ root_dir }}/README.md"
    html_file: "{{ docs_dir }}/index.html"

- name: Find all subdirectories within the pages directory
  find:
    paths: "{{ pages_dir }}"
    recurse: true
    file_type: directory
  register: pages_subdir

- name: Update pages
  include_tasks: update_page.yaml
  vars:
    page: "{{ item.path }}"
  with_items: "{{ pages_subdir.files }}"
